task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 12
remap_mscoco_category: True

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /home/HELUXING/Brain_project/data/cls-coco/train/
    ann_file: /home/HELUXING/Brain_project/data/cls-coco/Annotatioins_for_2D/train_coco_format.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 8
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /home/HELUXING/Brain_project/data/cls-coco/val/
    ann_file: /home/HELUXING/Brain_project/data/cls-coco/Annotatioins_for_2D/val_coco_format.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
