
train_dataloader:
  shuffle: True
  total_batch_size: 24 # 每个进程多少batch的意思 (4 * 8)
  num_workers: 0


val_dataloader:
  dataset:
    transforms:
      ops:
        - {type: Resize, size: [512, 512], }
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
  shuffle: False
  total_batch_size: 16
  num_workers: 0
