print_freq: 400
output_dir: './logs'
checkpoint_freq: 1


sync_bn: False
find_unused_parameters: True


use_amp: True
scaler:
  type: GradScaler
  enabled: True


use_ema: False
ema:
  type: ModelEMA
  decay: 0.9999
  warmups: 1000
